# Generated by Django 6.0.2 on 2026-04-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_firstname_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatar', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, default='Не указана', max_length=50, null=True, verbose_name='Текущая работа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, default='Новичок', max_length=50, null=True, verbose_name='Ранг'),
        ),
    ]
