# Generated by Django 6.0 on 2025-12-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=50)),
                ('is_auth', models.BooleanField(default=False)),
            ],
        ),
    ]
