# Generated by Django 6.0 on 2025-12-14 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_gmail_user_mail_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mail',
            new_name='gmail',
        ),
    ]
