# Generated by Django 6.0 on 2025-12-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gmail',
        ),
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
