# Generated by Django 6.0 on 2025-12-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_user_id_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
