# Generated by Django 6.0 on 2025-12-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(blank=True, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
