# Generated by Django 6.0 on 2025-12-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=None, upload_to='avatars/%Y%m%d'),
        ),
    ]
