# Generated by Django 6.0 on 2026-01-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/df.jpg', upload_to='media/avatars/%Y%m%d'),
        ),
    ]
