# Generated by Django 6.0 on 2026-01-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/df.jpg', upload_to='avatars/%Y%m%d/'),
        ),
    ]
