# Generated by Django 6.0 on 2025-12-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ImageField(blank=True, upload_to='images/%Y%m%d'),
        ),
    ]
