# Generated by Django 6.0 on 2025-12-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_img_post_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='author_user',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ImageField(blank=True, upload_to='media/%Y%m%d'),
        ),
    ]
