# Generated by Django 6.0.2 on 2026-04-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
